spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.cj.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "{cipher}5368ac684fa8b770bf6c27c06d960ff8cfa8b01ae003ca76e95429b6955fd686"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
security:
  basic:
    enabled: false
    
server:
  port: 8081

  logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
